### ISSUE TITLE
Skeleton issue with the Seige Ram actor

### ISSUE THREAD

**Issue by s0600204** [0ADMods/xiongnu#3]
One for the artists (as I don't have the knowledge to fix):

> ERROR: art/meshes/structural/trunk_ram.dae: Assertion not satisfied (line 393): failed requirement "recognised skeleton structure"
> ERROR: Could not load mesh 'art/meshes/structural/trunk_ram.dae'
> ERROR: CObjectEntry::BuildVariation(): Model art/meshes/structural/trunk_ram.dae failed to load
> ERROR: Failed to build prop model "structures/xion/siege_ram.xml" on actor "siege_ram_pivot"

To replicate:
1. Place a Xiongnu Siege Ram in Atlas (or build one in-game)

**Comment by wltonlopes** [comment]
Fixed error.
